---
- import_playbook: configure.ansible.yml

- name: Create directories on remote hosts
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Create metagraph-l0 directory
      file:
        path: /home/{{ ansible_user }}/code/metagraph-l0
        state: directory
      async: 300
      poll: 0

    - name: Create currency-l1 directory
      file:
        path: /home/{{ ansible_user }}/code/currency-l1
        state: directory
      async: 300
      poll: 0
      when: deploy_cl1 | bool

    - name: Create data-l1 directory
      file:
        path: /home/{{ ansible_user }}/code/data-l1
        state: directory
      async: 300
      poll: 0
      when: deploy_dl1 | bool

- name: Send JARs to remote hosts
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Sending cl-keytool.jar to metagraph-l0
      copy:
        src: ../../../docker/shared/jars/cl-keytool.jar
        dest: /home/{{ ansible_user }}/code/metagraph-l0

    - name: Sending cl-wallet.jar to metagraph-l0
      copy:
        src: ../../../docker/shared/jars/cl-wallet.jar
        dest: /home/{{ ansible_user }}/code/metagraph-l0

    - name: Sending metagraph-l0.jar to metagraph-l0
      copy:
        src: ../../../docker/shared/jars/metagraph-l0.jar
        dest: /home/{{ ansible_user }}/code/metagraph-l0

    - name: Sending cl-keytool.jar to currency-l1
      copy:
        src: ../../../docker/shared/jars/cl-keytool.jar
        dest: /home/{{ ansible_user }}/code/currency-l1
      when: deploy_cl1 | bool
    
    - name: Sending cl-wallet.jar to currency-l1
      copy:
        src: ../../../docker/shared/jars/cl-wallet.jar
        dest: /home/{{ ansible_user }}/code/currency-l1
      when: deploy_cl1 | bool

    - name: Sending currency-l1.jar to currency-l1
      copy:
        src: ../../../docker/shared/jars/currency-l1.jar
        dest: /home/{{ ansible_user }}/code/currency-l1/currency-l1.jar
      when: deploy_cl1 | bool

    - name: Sending cl-keytool.jar to data-l1
      copy:
        src: ../../../docker/shared/jars/cl-keytool.jar
        dest: /home/{{ ansible_user }}/code/data-l1
      when: deploy_dl1 | bool

    - name: Sending cl-wallet.jar to data-l1
      copy:
        src: ../../../docker/shared/jars/cl-wallet.jar
        dest: /home/{{ ansible_user }}/code/data-l1
      when: deploy_dl1 | bool

    - name: Sending data-l1.jar to data-l1
      copy:
        src: ../../../docker/shared/jars/data-l1.jar
        dest: /home/{{ ansible_user }}/code/data-l1/data-l1.jar
      when: deploy_dl1 | bool

- name: Send genesis information to remote hosts
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Sending metagraph l0 genesis.csv to metagraph-l0
      copy:
        src: ../../../../source/metagraph-l0/genesis/genesis.csv
        dest: /home/{{ ansible_user }}/code/metagraph-l0

    - name: Sending metagraph l0 genesis.snapshot to metagraph-l0
      copy:
        src: ../../../../source/metagraph-l0/genesis/genesis.snapshot
        dest: /home/{{ ansible_user }}/code/metagraph-l0

    - name: Sending metagraph l0 genesis.address to metagraph-l0
      copy:
        src: ../../../../source/metagraph-l0/genesis/genesis.address
        dest: /home/{{ ansible_user }}/code/metagraph-l0

- name: Send p12 files to remote node-1
  hosts: node-1
  gather_facts: false
  tasks:
    - name: Sending p12 file to metagraph-l0
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_GENESIS_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/metagraph-l0
        
    - name: Sending p12 file to currency-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_GENESIS_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/currency-l1
      when: deploy_cl1 | bool

    - name: Sending p12 file to data-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_GENESIS_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/data-l1
      when: deploy_dl1 | bool

- name: Send p12 files to remote node-2
  hosts: node-2
  gather_facts: false
  tasks:
    - name: Sending p12 file to metagraph-l0
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_2_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/metagraph-l0
        
    - name: Sending p12 file to currency-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_2_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/currency-l1
      when: deploy_cl1 | bool

    - name: Sending p12 file to data-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_2_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/data-l1
      when: deploy_dl1 | bool

- name: Send p12 files to remote node-3
  hosts: node-3
  gather_facts: false
  tasks:
    - name: Sending p12 file to metagraph-l0
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_3_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/metagraph-l0
        
    - name: Sending p12 file to currency-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_3_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/currency-l1
      when: deploy_cl1 | bool

    - name: Sending p12 file to data-l1
      copy:
        src: ../../../../source/p12-files/{{ lookup('env', 'P12_NODE_3_FILE_NAME') }}
        dest: /home/{{ ansible_user }}/code/data-l1
      when: deploy_dl1 | bool