# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  global-l0-1:
    platform: linux/amd64
    container_name: global-l0-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/global-l0/Dockerfile
    image: global-l0
    environment:
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
      - CL_ENV=dev
    volumes:
      - ../shared/jars:/code/jars/
      - ../../../source/global-l0/tessellation:/code/codebase/tessellation
      - ../../../source/global-l0/genesis:/code/genesis/.
      - ../../../scripts/start-containers/global:/code/start_scripts
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      custom-network:
        ipv4_address: 172.50.0.5
    command: >
       sh -c 'mv start_scripts/start.sh . && chmod a+x start.sh && ./start.sh'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://global-l0-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true